spring.application.name=Back-end

spring.config.import=file:env.properties

spring.datasource.url=jdbc:postgresql://localhost:5432/Esame-finale
spring.datasource.username=postgres
spring.datasource.password=${postgresql.password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
cloudinary.cloud_name=dezrvwhtj
cloudinary.api_key=714486466853964
cloudinary.api_secret=6T8FrdmJhQWoZYIzln69iJ8AbVI

jwt.duration=900000
jwt.secret=zampettaMoltoCarinaDiUnCaneMoltoFelice

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB